version: '3.2'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
  compressed:
    build:
      context: .
      dockerfile: Dockerfile.compressed
    ports:
      - 9000:9000
  multistaged:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000