apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
     app: myapp
spec:
  containers:
  - image: myapp:productionImage
    name: myapp-prod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
