name: test1

on:
  push:
    branches: [ "main" ]           # Trigger on push to the main branch
  pull_request:
    branches: [ "main" ]           # Trigger on pull request to main
  workflow_dispatch:               # Allow manual execution from GitHub UI

jobs:
  build-and-scan:
    runs-on: ubuntu-latest         # Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Set up Docker Buildx for advanced build support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker images defined in your Compose file
      - name: Run docker compose to build images
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./session-3/part-3/docker-compose.yaml"  
